In [75]:
import pandas as pd

df = pd.read_csv(r'/Users/dimka/Desktop/проект/load_data.csv')

In [76]:
df

,id,premium,name,area,salary,published_at,employer,schedule,professional_roles,experience,employment,start_year
0,90646228,0,Junior Product Manager,Москва,127840,13-12-2023,Кухня на районе,Полный день,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0
1,90504793,0,Стажер Product Manager,Москва,131101,08-12-2023,Mindbox,Удаленная работа,73,"{'id': 'noExperience', 'name': 'Нет опыта'}",Стажировка,NaN
2,90005929,0,Junior Product Manager,Москва,134932,27-11-2023,Grabber,Полный день,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0
3,90472971,0,Junior Product manager,Москва,166715,08-12-2023,EGGHEADS,Удаленная работа,73,"{'id': 'noExperience', 'name': 'Нет опыта'}",Полная занятость,NaN
4,90110864,0,Product менеджер,Москва,232552,29-11-2023,Консоль.Про,Удаленная работа,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
395,91083126,0,Lead Product Manager,Москва,119459,27-12-2023,«UZUM TECHNOLOGIES».,Полный день,73,"{'id': 'between3And6', 'name': 'От 3 до 6 лет'}",Полная занятость,3.0
396,90981138,0,Project Manager / Product Manager,Москва,114021,25-12-2023,Жанкенова Оксана Дмитриевна,Удаленная работа,107,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0
397,91047518,0,Product Designer (UX/UI дизайнер),Москва,233660,26-12-2023,Таргет,Удаленная работа,34,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0
398,90203602,0,Junior Product Analyst,Москва,151178,01-12-2023,L’etoile Digital,Полный день,164,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0
399,90464648,0,Product manager,Москва,154779,08-12-2023,Neiry,Полный день,73,"{'id': 'between3And6', 'name': 'От 3 до 6 лет'}",Полная занятость,3.0

In [77]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoded_schedule = encoder.fit_transform(df["schedule"].values.reshape(-1, 1)).toarray()

schedule_names = encoder.get_feature_names_out(['schedule'])
schedule_df = pd.DataFrame(encoded_schedule, columns=schedule_names)
df = pd.concat([df, schedule_df], axis=1)
df.drop("schedule", axis=1, inplace=True)
df

,id,premium,name,area,salary,published_at,employer,professional_roles,experience,employment,start_year,schedule_Полный день,schedule_Удаленная работа
0,90646228,0,Junior Product Manager,Москва,127840,13-12-2023,Кухня на районе,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0,1.0,0.0
1,90504793,0,Стажер Product Manager,Москва,131101,08-12-2023,Mindbox,73,"{'id': 'noExperience', 'name': 'Нет опыта'}",Стажировка,NaN,0.0,1.0
2,90005929,0,Junior Product Manager,Москва,134932,27-11-2023,Grabber,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0,1.0,0.0
3,90472971,0,Junior Product manager,Москва,166715,08-12-2023,EGGHEADS,73,"{'id': 'noExperience', 'name': 'Нет опыта'}",Полная занятость,NaN,0.0,1.0
4,90110864,0,Product менеджер,Москва,232552,29-11-2023,Консоль.Про,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,91083126,0,Lead Product Manager,Москва,119459,27-12-2023,«UZUM TECHNOLOGIES».,73,"{'id': 'between3And6', 'name': 'От 3 до 6 лет'}",Полная занятость,3.0,1.0,0.0
396,90981138,0,Project Manager / Product Manager,Москва,114021,25-12-2023,Жанкенова Оксана Дмитриевна,107,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0,0.0,1.0
397,91047518,0,Product Designer (UX/UI дизайнер),Москва,233660,26-12-2023,Таргет,34,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0,0.0,1.0
398,90203602,0,Junior Product Analyst,Москва,151178,01-12-2023,L’etoile Digital,164,"{'id': 'between1And3', 'name': 'От 1 года до 3...",Полная занятость,1.0,1.0,0.0
399,90464648,0,Product manager,Москва,154779,08-12-2023,Neiry,73,"{'id': 'between3And6', 'name': 'От 3 до 6 лет'}",Полная занятость,3.0,1.0,0.0

In [78]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoded_employment = encoder.fit_transform(df["employment"].values.reshape(-1, 1)).toarray()

employment_names = encoder.get_feature_names_out(['employment'])
employment_df = pd.DataFrame(encoded_employment, columns=employment_names)
df = pd.concat([df, employment_df], axis=1)
df.drop("employment", axis=1, inplace=True)
df

,id,premium,name,area,salary,published_at,employer,professional_roles,experience,start_year,schedule_Полный день,schedule_Удаленная работа,employment_Полная занятость,employment_Стажировка
0,90646228,0,Junior Product Manager,Москва,127840,13-12-2023,Кухня на районе,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",1.0,1.0,0.0,1.0,0.0
1,90504793,0,Стажер Product Manager,Москва,131101,08-12-2023,Mindbox,73,"{'id': 'noExperience', 'name': 'Нет опыта'}",NaN,0.0,1.0,0.0,1.0
2,90005929,0,Junior Product Manager,Москва,134932,27-11-2023,Grabber,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",1.0,1.0,0.0,1.0,0.0
3,90472971,0,Junior Product manager,Москва,166715,08-12-2023,EGGHEADS,73,"{'id': 'noExperience', 'name': 'Нет опыта'}",NaN,0.0,1.0,1.0,0.0
4,90110864,0,Product менеджер,Москва,232552,29-11-2023,Консоль.Про,73,"{'id': 'between1And3', 'name': 'От 1 года до 3...",1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,91083126,0,Lead Product Manager,Москва,119459,27-12-2023,«UZUM TECHNOLOGIES».,73,"{'id': 'between3And6', 'name': 'От 3 до 6 лет'}",3.0,1.0,0.0,1.0,0.0
396,90981138,0,Project Manager / Product Manager,Москва,114021,25-12-2023,Жанкенова Оксана Дмитриевна,107,"{'id': 'between1And3', 'name': 'От 1 года до 3...",1.0,0.0,1.0,1.0,0.0
397,91047518,0,Product Designer (UX/UI дизайнер),Москва,233660,26-12-2023,Таргет,34,"{'id': 'between1And3', 'name': 'От 1 года до 3...",1.0,0.0,1.0,1.0,0.0
398,90203602,0,Junior Product Analyst,Москва,151178,01-12-2023,L’etoile Digital,164,"{'id': 'between1And3', 'name': 'От 1 года до 3...",1.0,1.0,0.0,1.0,0.0
399,90464648,0,Product manager,Москва,154779,08-12-2023,Neiry,73,"{'id': 'between3And6', 'name': 'От 3 до 6 лет'}",3.0,1.0,0.0,1.0,0.0

In [79]:
df.drop("experience", axis=1, inplace=True)

In [80]:
encoder = OneHotEncoder()
encoded_area = encoder.fit_transform(df["area"].values.reshape(-1, 1)).toarray()

area_names = encoder.get_feature_names_out(['area'])
area_df = pd.DataFrame(encoded_area, columns=area_names)
df = pd.concat([df, area_df], axis=1)
df.drop("area", axis=1, inplace=True)
df

,id,premium,name,salary,published_at,employer,professional_roles,start_year,schedule_Полный день,schedule_Удаленная работа,employment_Полная занятость,employment_Стажировка,area_Москва
0,90646228,0,Junior Product Manager,127840,13-12-2023,Кухня на районе,73,1.0,1.0,0.0,1.0,0.0,1.0
1,90504793,0,Стажер Product Manager,131101,08-12-2023,Mindbox,73,NaN,0.0,1.0,0.0,1.0,1.0
2,90005929,0,Junior Product Manager,134932,27-11-2023,Grabber,73,1.0,1.0,0.0,1.0,0.0,1.0
3,90472971,0,Junior Product manager,166715,08-12-2023,EGGHEADS,73,NaN,0.0,1.0,1.0,0.0,1.0
4,90110864,0,Product менеджер,232552,29-11-2023,Консоль.Про,73,1.0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,91083126,0,Lead Product Manager,119459,27-12-2023,«UZUM TECHNOLOGIES».,73,3.0,1.0,0.0,1.0,0.0,1.0
396,90981138,0,Project Manager / Product Manager,114021,25-12-2023,Жанкенова Оксана Дмитриевна,107,1.0,0.0,1.0,1.0,0.0,1.0
397,91047518,0,Product Designer (UX/UI дизайнер),233660,26-12-2023,Таргет,34,1.0,0.0,1.0,1.0,0.0,1.0
398,90203602,0,Junior Product Analyst,151178,01-12-2023,L’etoile Digital,164,1.0,1.0,0.0,1.0,0.0,1.0
399,90464648,0,Product manager,154779,08-12-2023,Neiry,73,3.0,1.0,0.0,1.0,0.0,1.0

In [86]:
df["schedule_Полный день"] = df['schedule_Полный день'].astype('int')
df["schedule_Удаленная работа"] = df['schedule_Удаленная работа'].astype('int')
df["employment_Полная занятость"] = df['employment_Полная занятость'].astype('int')
df["employment_Стажировка"] = df['employment_Стажировка'].astype('int')
df["area_Москва"] = df['area_Москва'].astype('int')
df.dtypes

id                               int64
premium                          int64
name                            object
salary                           int64
published_at                    object
employer                        object
professional_roles               int64
start_year                     float64
schedule_Полный день             int64
schedule_Удаленная работа        int64
employment_Полная занятость      int64
employment_Стажировка            int64
area_Москва                      int64
dtype: object

In [87]:
df.to_csv(r'/Users/dimka/Desktop/проект/prepared_data/prepared_data.csv', index = False)